--zachariah loy yiqi (s10257183D)

-- create task to refresh the stage's current
CREATE OR REPLACE TASK TEAM3_TABLE_TRIGGERED_TASK  
WAREHOUSE = TEAM3_WH
WHEN SYSTEM$STREAM_HAS_DATA('TEMP_TABLE_STREAM')
AS
CALL TEAM3_STAGE_REFRESHER();

-- this task runs after refreshing the stage and after the task 
CREATE OR REPLACE TASK TEAM3_TABLE_APPENDER_TASK
WAREHOUSE = TEAM3_WH 
AFTER TEAM3_TABLE_TRIGGERED_TASK
AS
CALL TEAM3_TABLE_APPENDER();
