-- Jaden Khoo (S10258662)
-- get the credits used for the different warehouse
-- using the correct role for the querying of the credits used
USE SCHEMA SNOWFLAKE.ACCOUNT_USAGE;
SELECT WAREHOUSE_NAME,   
SUM(CREDITS_USED_COMPUTE) AS CREDITS_USED_COMPUTE_SUM
FROM ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE WAREHOUSE_NAME = 'TEAM3_WH' 
OR WAREHOUSE_NAME = 'FERRET_WH' 
OR WAREHOUSE_NAME = 'FINCH_WH' 
OR WAREHOUSE_NAME = 'FLAMINGO_WH'
OR WAREHOUSE_NAME = 'FALCON_WH'
GROUP BY 1
ORDER BY 2 DESC;

-- get the excecution time
-- using the correct role for the querying of the credits used
USE SCHEMA TEAM3_DB.INFORMATION_SCHEMA;
WITH WAREHOUSE_SIZE AS
(
SELECT WAREHOUSE_SIZE, "CREDITS/HOUR"
FROM (
SELECT 'X-Small' AS WAREHOUSE_SIZE, 1 AS "CREDITS/HOUR"
UNION ALL
SELECT 'Small' AS WAREHOUSE_SIZE, 2 AS "CREDITS/HOUR"
UNION ALL
SELECT 'Medium' AS WAREHOUSE_SIZE, 4 AS "CREDITS/HOUR"
UNION ALL
SELECT 'Large' AS WAREHOUSE_SIZE, 8 AS "CREDITS/HOUR"
UNION ALL
SELECT 'X-Large' AS WAREHOUSE_SIZE, 16 AS "CREDITS/HOUR"
UNION ALL
SELECT '2X-Large' AS WAREHOUSE_SIZE, 32 AS "CREDITS/HOUR"
UNION ALL
SELECT '3X-Large' AS WAREHOUSE_SIZE, 64 AS "CREDITS/HOUR"
UNION ALL
SELECT '4X-Large' AS WAREHOUSE_SIZE, 128 AS "CREDITS/HOUR"
)
),
QUERY_HISTORY AS
(
SELECT 
QUERY_ID,
QUERY_TEXT,
START_TIME,
END_TIME,
USER_NAME,
ROLE_NAME,
DATABASE_NAME,
WAREHOUSE_SIZE,
EXECUTION_TIME,
(EXECUTION_TIME/(1000)) as EXECUTION_TIME_SECONDS
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())
WHERE START_TIME >= DATEADD(month, -2, CURRENT_TIMESTAMP())
)
SELECT 
QH.QUERY_ID,
QH.START_TIME,
QH.END_TIME,
QH.QUERY_TEXT,
QH.USER_NAME,
QH.ROLE_NAME,
WS.WAREHOUSE_SIZE,
WS."CREDITS/HOUR",
(QH.EXECUTION_TIME/(1000*60*60))*WS."CREDITS/HOUR" as CREDITS_CONSUMED
FROM QUERY_HISTORY QH
LEFT JOIN WAREHOUSE_SIZE WS ON WS.WAREHOUSE_SIZE = QH.WAREHOUSE_SIZE
ORDER BY CREDITS_CONSUMED DESC



-- to get the time of the query
-- using the correct role for the querying of the credits used
USE SCHEMA TEAM3_DB.INFORMATION_SCHEMA;
SELECT 
QUERY_ID,
QUERY_TEXT,
USER_NAME,
START_TIME,
END_TIME,
DATABASE_NAME,
WAREHOUSE_SIZE,
(EXECUTION_TIME/(1000)) as EXECUTION_TIME_SECONDS
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())
WHERE START_TIME >= DATEADD(month, -2, CURRENT_TIMESTAMP())
ORDER BY START_TIME DESC;
    TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())
WHERE 
    START_TIME >= DATEADD(month, -2, CURRENT_TIMESTAMP())
ORDER BY 
    START_TIME DESC;
