USE ROLE ACCOUNTADMIN;
-- creating the roles
CREATE ROLE Team3_Tester;
CREATE ROLE Team3_Developer;
CREATE ROLE Team3_Master_Admin;

-- Grant Tester role read-only access
-- Grant privileges on Database
GRANT USAGE, MONITOR ON DATABASE TEAM3_DB TO ROLE Team3_Tester;
-- Grant privileges on Schema
-- main schema
GRANT USAGE, MONITOR ON SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Tester;
GRANT SELECT ON ALL TABLES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Tester;
GRANT SELECT ON ALL VIEWS IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Tester;
GRANT USAGE, READ ON ALL STAGES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Tester;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Tester;
-- Allow full control over the warehouse
GRANT USAGE ON WAREHOUSE TEAM3_WH TO ROLE Team3_Tester;


-- Grant Developer role privileges for development work like inserting and updating
-- inherit the role from the traning role
GRANT ROLE TRAINING_ROLE TO ROLE Team3_Developer;
-- Grant privileges on Database
GRANT ALL ON DATABASE TEAM3_DB TO ROLE Team3_Developer;
-- Grant privileges on Schema
-- main schema
GRANT ALL ON SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Developer;
GRANT ALL ON ALL TABLES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Developer;
GRANT ALL ON FUTURE TABLES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Developer;
GRANT ALL ON FUTURE DYNAMIC TABLES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA to role Team3_Developer;
GRANT ALL ON ALL VIEWS IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Developer;
GRANT ALL ON ALL STAGES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Developer;
GRANT ALL ON INTEGRATION git_api_integration_team3 TO ROLE Team3_Developer;
GRANT ALL ON PIPE TEAM3_PIPELINE TO ROLE Team3_Developer;
GRANT ALL ON ALL STREAMS IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Developer;
GRANT ALL ON ALL TASKS IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Developer;
GRANT ALL ON ALL PROCEDURES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
-- backup scema
GRANT ALL ON SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Developer;
GRANT ALL ON ALL TABLES IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Developer;
GRANT ALL ON FUTURE TABLES IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Developer;
GRANT ALL ON FUTURE DYNAMIC TABLES IN SCHEMA TEAM3_DB.TEAM3_BACKUP to role Team3_Developer;
GRANT ALL ON ALL VIEWS IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Developer;
GRANT ALL ON ALL STAGES IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Developer;
GRANT ALL ON ALL STREAMS IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Developer;
GRANT ALL ON ALL TASKS IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Developer;
GRANT ALL ON ALL PROCEDURES IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
-- Allow full control over the warehouse
GRANT ALL ON WAREHOUSE TEAM3_WH TO ROLE Team3_Developer;


-- Grant Master_Admin full administrative privileges
-- inherit the role from the traning role
GRANT ROLE TRAINING_ROLE TO ROLE Team3_Master_Admin;
-- Grant privileges on Database
GRANT OWNERSHIP ON DATABASE TEAM3_DB TO ROLE Team3_Master_Admin;
GRANT ALL ON DATABASE TEAM3_DB TO ROLE Team3_Master_Admin;
-- main schema
GRANT OWNERSHIP ON SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
GRANT ALL ON SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
-- tables
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
GRANT ALL ON ALL TABLES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
GRANT ALL ON FUTURE TABLES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
-- dynamic tables
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA to role Team3_Master_Admin;
GRANT ALL ON FUTURE DYNAMIC TABLES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA to role Team3_Master_Admin;
-- views
GRANT ALL ON ALL VIEWS IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
GRANT ALL ON FUTURE VIEWS IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
-- stage
GRANT ALL ON ALL STAGES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
GRANT ALL ON FUTURE STAGES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
-- github
GRANT OWNERSHIP ON SECRET TEAM3_DB.TEAM3_SCHEMA.github_secret_team3 TO ROLE Team3_Master_Admin;
GRANT ALL ON SECRET TEAM3_DB.TEAM3_SCHEMA.github_secret_team3 TO ROLE Team3_Master_Admin;
GRANT OWNERSHIP ON INTEGRATION git_api_integration_team3 TO ROLE Team3_Master_Admin;
GRANT ALL ON INTEGRATION git_api_integration_team3 TO ROLE Team3_Master_Admin;
GRANT OWNERSHIP ON GIT REPOSITORY TEAM3_DB.TEAM3_SCHEMA.VelocityNet TO ROLE Team3_Master_Admin;
GRANT ALL ON GIT REPOSITORY TEAM3_DB.TEAM3_SCHEMA.VelocityNet TO ROLE Team3_Master_Admin;
-- pipeline
GRANT ALL ON PIPE TEAM3_PIPELINE TO ROLE Team3_Master_Admin;
-- streams
GRANT ALL ON ALL STREAMS IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
GRANT ALL ON FUTURE STREAMS IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
-- task
GRANT ALL ON ALL TASKS IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
GRANT ALL ON FUTURE TASKS IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
-- stored procedures
GRANT ALL ON ALL PROCEDURES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA TEAM3_DB.TEAM3_SCHEMA TO ROLE Team3_Master_Admin;
-- backup scema
GRANT OWNERSHIP ON SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
GRANT ALL ON SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
-- table
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
GRANT ALL ON ALL TABLES IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
GRANT ALL ON FUTURE TABLES IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
-- dynamic table
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA TEAM3_DB.TEAM3_BACKUP to role Team3_Master_Admin;
GRANT ALL ON FUTURE DYNAMIC TABLES IN SCHEMA TEAM3_DB.TEAM3_BACKUP to role Team3_Master_Admin;
-- views
GRANT ALL ON ALL VIEWS IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
GRANT ALL ON FUTURE VIEWS IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
-- stage
GRANT ALL ON ALL STAGES IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
GRANT ALL ON FUTURE STAGES IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
-- stream
GRANT ALL ON ALL STREAMS IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
GRANT ALL ON FUTURE STREAMS IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
-- task
GRANT ALL ON ALL TASKS IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
GRANT ALL ON FUTURE TASKS IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
-- stored procedures
GRANT ALL ON ALL PROCEDURES IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA TEAM3_DB.TEAM3_BACKUP TO ROLE Team3_Master_Admin;
-- Allow full control over the warehouse
GRANT OWNERSHIP ON WAREHOUSE TEAM3_WH TO ROLE Team3_Master_Admin;
GRANT ALL ON WAREHOUSE TEAM3_WH TO ROLE Team3_Master_Admin;
GRANT OWNERSHIP ON WAREHOUSE TEAM3_POWERBI_WH TO ROLE Team3_Master_Admin;
GRANT ALL ON WAREHOUSE TEAM3_POWERBI_WH TO ROLE Team3_Master_Admin;
-- Grant the ability to manage roles and users and create resource monintor
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE Team3_Master_Admin;
GRANT MONITOR ON ACCOUNT TO ROLE Team3_Master_Admin;
-- Allow execution of task
GRANT EXECUTE TASK ON ACCOUNT TO ROLE TEAM3_MASTER_ADMIN;


SHOW GRANTS TO ROLE Team3_Master_Admin;


-- Grant the roles to the users
GRANT ROLE Team3_Tester TO USER FERRET;
GRANT ROLE Team3_Tester TO USER FINCH;
GRANT ROLE Team3_Tester TO USER FLAMINGO;
GRANT ROLE Team3_Tester TO USER FALCON;

GRANT ROLE Team3_Developer TO USER FERRET;
GRANT ROLE Team3_Developer TO USER FINCH;
GRANT ROLE Team3_Developer TO USER FLAMINGO;
GRANT ROLE Team3_Developer TO USER FALCON;

GRANT ROLE Team3_Master_Admin TO USER FERRET;
GRANT ROLE Team3_Master_Admin TO USER FINCH;
GRANT ROLE Team3_Master_Admin TO USER FLAMINGO;
GRANT ROLE Team3_Master_Admin TO USER FALCON;

GRANT ROLE Team3_Master_Admin TO USER FERRET;
GRANT ROLE Team3_Master_Admin TO USER FINCH;
GRANT ROLE Team3_Master_Admin TO USER FLAMINGO;
GRANT ROLE Team3_Master_Admin TO USER FALCON;
