--create stored procedure to analyse query performance given input query block
CREATE OR REPLACE PROCEDURE QUERY_PERFORMANCE(QUERY_STRING STRING)
RETURNS TABLE()
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN

BEGIN TRANSACTION;
EXECUTE IMMEDIATE :QUERY_STRING;
ROLLBACK;

LET RESULTS RESULTSET := (SELECT * FROM TABLE(INFORMATION_SCHEMA.query_history()) WHERE START_TIME >= DATE_TRUNC('DAY', CURRENT_TIMESTAMP) AND 
start_time > (SELECT START_TIME FROM TABLE(INFORMATION_SCHEMA.query_history()) WHERE QUERY_TEXT = 'BEGIN TRANSACTION;' order by start_time DESC LIMIT 1) AND 
start_time < (SELECT START_TIME FROM TABLE(INFORMATION_SCHEMA.query_history()) WHERE QUERY_TEXT = 'ROLLBACK;' order by start_time DESC LIMIT 1)
order by start_time DESC);

RETURN TABLE(RESULTS);
END;
$$;
