COPY INTO PURCHASING_PRODUCTVENDOR
FROM @S3_STAGE_TEAM3
FILE_FORMAT = CSVFILEFORMATTEAM3
PATTERN = 'PurchasingProductVendor.csv';

COPY INTO PURCHASING_PURCHASEORDERDETAIL
FROM @S3_STAGE_TEAM3
FILE_FORMAT = CSVFILEFORMATTEAM3
PATTERN = 'PurchasingPurchaseOrderDetail.csv';

COPY INTO PURCHASING_PURCHASEORDERHEADER
FROM @S3_STAGE_TEAM3
FILE_FORMAT = CSVFILEFORMATTEAM3
PATTERN = 'PurchasingPurchaseOrderHeader.csv';

COPY INTO PURCHASING_SHIPMETHOD
FROM @S3_STAGE_TEAM3
FILE_FORMAT = CSVFILEFORMATTEAM3
PATTERN = 'PurchasingShipMethod.csv';

COPY INTO PURCHASING_VENDOR
FROM @S3_STAGE_TEAM3
FILE_FORMAT = CSVFILEFORMATTEAM3
PATTERN = 'PurchasingVendor.csv';

COPY INTO HUMANRESOURCES_DEPARTMENT
FROM @S3_STAGE_TEAM3
PATTERN = 'HumanResourcesDepartment.csv'
FILE_FORMAT = CSVFILEFORMATTEAM3

COPY INTO HUMANRESOURCES_EMPLOYEE
FROM @S3_STAGE_TEAM3
PATTERN = 'HumanResourcesEmployee.csv'
FILE_FORMAT = CSVFILEFORMATTEAM3

COPY INTO SALES_SPECIALOFFER
FROM @S3_STAGE_TEAM3
PATTERN = 'SalesSpecialOffer.csv'
FILE_FORMAT = CSVFILEFORMATTEAM3

COPY INTO SALES_SPECIALOFFERPRODUCT
FROM @S3_STAGE_TEAM3
PATTERN = 'SalesSpecialOfferProduct.csv'
FILE_FORMAT = CSVFILEFORMATTEAM3
