COPY INTO PURCHASING_PRODUCTVENDOR
FROM @S3_STAGE_TEAM3
FILE_FORMAT = CSVFILEFORMATTEAM3
PATTERN = 'PurchasingProductVendor.csv';

COPY INTO PURCHASING_PURCHASEORDERDETAIL
FROM @S3_STAGE_TEAM3
FILE_FORMAT = CSVFILEFORMATTEAM3
PATTERN = 'PurchasingPurchaseOrderDetail.csv';

COPY INTO PURCHASING_PURCHASEORDERHEADER
FROM @S3_STAGE_TEAM3
FILE_FORMAT = CSVFILEFORMATTEAM3
PATTERN = 'PurchasingPurchaseOrderHeader.csv';

COPY INTO PURCHASING_SHIPMETHOD
FROM @S3_STAGE_TEAM3
FILE_FORMAT = CSVFILEFORMATTEAM3
PATTERN = 'PurchasingShipMethod.csv';

COPY INTO PURCHASING_VENDOR
FROM @S3_STAGE_TEAM3
FILE_FORMAT = CSVFILEFORMATTEAM3
PATTERN = 'PurchasingVendor.csv';
