name: Continuous Deployment with Prometheus Monitoring

on:
  push:
    branches:
      - main

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_LOGIN_NAME: ${{ secrets.DOCKER_LOGIN_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Clean Up Existing Containers
      run: |
        docker stop prometheus-container || true
        docker rm prometheus-container || true
        docker stop app-container || true
        docker rm app-container || true

    - name: Build Application Docker Image
      run: docker build --rm --platform linux/amd64 -t app-container -f src/docker/Dockerfile .

    - name: Create Prometheus Configuration
      run: |
        cat <<EOF > prometheus.yml
        global:
          scrape_interval: 15s
        scrape_configs:
          - job_name: 'application'
            static_configs:
              - targets: ['app-container:8000']  # Application metrics exposed on port 8000
        EOF

    - name: Create Docker Network
      run: docker network create custom-network || true

    - name: Run Application Container
      run: docker run --net custom-network -d --name app-container -p 8000:8000 app-container

    - name: Run Prometheus Container
      run: docker run --net custom-network -d --name prometheus-container -p 9090:9090 -v $(pwd)/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus

  monitor:
    runs-on: ubuntu-latest
    needs: deploy  # Run only after the deploy job completes

    steps:
    - name: Test Prometheus Connection
      run: |
        curl -s http://localhost:9090/api/v1/status/buildinfo && echo "Prometheus is connected" || echo "Prometheus server not connected"

    - name: Query Prometheus for Metrics
      run: |
        QUERY_RESULT=$(curl -s "http://localhost:9090/api/v1/query?query=up")
        echo "Prometheus query result: $QUERY_RESULT"

    - name: Validate Application Metrics
      run: |
        echo "Validating Prometheus metrics..."
        APP_UP=$(curl -s "http://localhost:9090/api/v1/query?query=my_app_up")
        if [ "$APP_UP" != "1" ]; then
          echo "Application is not running properly!"
          exit 1
        fi
        echo "Application metrics validated successfully."

