name: Continuous Deployment Of Docker Image to Snowpark Container Services

on: [push]

# Set Environmental Variables
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_LOGIN_NAME: ${{ secrets.DOCKER_LOGIN_NAME }}
  SNOWFLAKE_CONNECTIONS_DUMMY_ACCOUNT: ${{ secrets.TGT_ACCOUNT }}
  SNOWFLAKE_CONNECTIONS_DUMMY_USER: ${{ secrets.TGT_USER }}
  SNOWFLAKE_CONNECTIONS_DUMMY_PASSWORD: ${{ secrets.TGT_PASSWORD }}
  SNOWFLAKE_CONNECTIONS_DUMMY_DATABASE: "TEAM3_DB"
  SNOWFLAKE_CONNECTIONS_DUMMY_SCHEMA: "TEAM3_SCHEMA"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Docker Login
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - name: Run a command
      run: echo "User=$DOCKER_USER"
    - name: Docker build image
      run: docker build --rm --platform linux/amd64 -t streamlit-app -f src/docker/Dockerfile .

    # Snowflake CLI installation
    - uses: Snowflake-Labs/snowflake-cli-action@v1.5
      with:
        cli-version: "latest"
        default-config-file-path: "config.toml"

    # Use the CLI
    - name: Test version
      run: snow --version
    - name: Test Connection
      env:
        SNOWFLAKE_CONNECTIONS_DUMMY_ROLE: TEAM3_MASTER_ADMIN
        SNOWFLAKE_CONNECTIONS_DUMMY_WAREHOUSE: TEAM3_WH
        SNOWFLAKE_CONNECTIONS_DUMMY_DATABASE: ${{ env.SNOWFLAKE_CONNECTIONS_DUMMY_DATABASE }}  # Reference database
        SNOWFLAKE_CONNECTIONS_DUMMY_SCHEMA: ${{ env.SNOWFLAKE_CONNECTIONS_DUMMY_SCHEMA }}  # Reference schema
      run: snow connection test --connection Dummy




    # Install dependencies including Black and Pylint
    - name: Install dependencies
      run: |
        pip install -r requirements.txt


    # Pylint - code quality check
    - name: Run Pylint for code quality
      run: |
        pylint $(find . -name "*.py")  # Run Pylint on all Python files
