name: Basic deploy
on:
  push:
    branches: [ main ]

jobs:
  Prometheus-Deploy:
    runs-on: ubuntu-latest
    steps:
    - id: deploy
      name: Deploy
      uses: bitovi/github-actions-deploy-prometheus@v3.1.0
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env_ghs: ${{ secrets.DOT_ENV }}
