name: Format, Lint, and Coverage Checks

on: [push, pull_request]

jobs:
  lint-and-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install flake8 flake8-nb black pytest pytest-cov nbconvert

    # Convert Jupyter Notebook to Python script
    - name: Convert Jupyter Notebook to Python script
      run: |
        mkdir -p Code/DataCleaning/AUTO_TRANSFORMATION/converted_notebooks
        jupyter nbconvert --to script \
          Code/DataCleaning/AUTO_TRANSFORMATION/notebook_app.ipynb \
          --output-dir=Code/DataCleaning/AUTO_TRANSFORMATION/converted_notebooks \
          --output=notebook_app

        # Ensure correct file extension
        if [ -f Code/DataCleaning/AUTO_TRANSFORMATION/converted_notebooks/notebook_app.py.txt ]; then
          mv Code/DataCleaning/AUTO_TRANSFORMATION/converted_notebooks/notebook_app.py.txt \
             Code/DataCleaning/AUTO_TRANSFORMATION/converted_notebooks/notebook_app.py
        fi

    - name: Verify Converted Files
      run: ls -la Code/DataCleaning/AUTO_TRANSFORMATION/converted_notebooks/

    # Lint with flake8
    - name: Lint Python files
      run: flake8 . --max-line-length=120
      continue-on-error: true

    # Check formatting with black
    - name: Check formatting with black
      run: black . --check --line-length 120 -vv
      continue-on-error: true

    #  Run tests with coverage
    - name: Run tests and generate coverage report
      run: |
        pytest --cov=Code/DataCleaning/AUTO_TRANSFORMATION/converted_notebooks/notebook_app.py \
               --cov-report=xml \
               --cov-report=html:Code/DataCleaning/AUTO_TRANSFORMATION/converted_notebooks/htmlcov
      continue-on-error: true

    # Upload coverage reports
    - name: Upload Coverage Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: Code/DataCleaning/AUTO_TRANSFORMATION/converted_notebooks/htmlcov/
